import { isIOS, isAndroid } from '../utils/deviceInfo';

export const STATUS_COLORS = {
	online: '#2de0a5',
	busy: '#f5455c',
	away: '#ffd21f',
	offline: '#cbced1'
};

export const SWITCH_TRACK_COLOR = {
	false: isAndroid ? '#f5455c' : null,
	true: '#2de0a5'
};

export const themes = {
	light: {
		backgroundColor: '#ffffff',
		focusedBackground: '#ffffff',
		chatComponentBackground: '#f3f4f5',
		auxiliaryBackground: '#efeff4',
		bannerBackground: '#f1f2f4',
		titleText: '#0d0e12',
		bodyText: '#2f343d',
		backdropColor: '#000000',
		dangerColor: '#f5455c',
		successColor: '#2de0a5',
		borderColor: '#e1e5e8',
		controlText: '#54585e',
		auxiliaryText: '#9ca2a8',
		infoText: '#6d6d72',
		tintColor: '#1d74f5',
		auxiliaryTintColor: '#caced1',
		actionTintColor: '#1d74f5',
		secondaryTintColor: '#6A7074',

		separatorColor: '#cbcbcc',
		navbarBackground: '#ffffff',
		headerBorder: '#B2B2B2',
		headerBackground: isIOS ? '#f8f8f8' : '#2f343d',
		headerSecondaryBackground: '#ffffff',
		headerTintColor: isAndroid ? '#ffffff' : '#1d74f5',
		headerTitleColor: isAndroid ? '#ffffff' : '#0d0e12',
		headerSecondaryText: isAndroid ? '#9ca2a8' : '#1d74f5',
		toastBackground: '#0C0D0F',
		videoBackground: '#1f2329',
		favoriteBackground: '#ffbb00',
		hideBackground: '#54585e',
		messageboxBackground: '#ffffff',
		searchboxBackground: '#E6E6E7',
		buttonBackground: '#414852',
		buttonText: '#ffffff'
	},
	dark: {
		backgroundColor: '#2F3234',
		focusedBackground: '#6A7074',
		chatComponentBackground: '#6A7074',
		auxiliaryBackground: '#6A7074',
		bannerBackground: '#6A7074',
		titleText: '#FFFFFF',
		bodyText: '#e8ebed',
		backdropColor: '#000000',
		dangerColor: '#f5455c',
		successColor: '#2de0a5',
		borderColor: '#6A7074',
		controlText: '#dadde6',
		auxiliaryText: '#FFFFFF',
		infoText: '#6D6D72',
		tintColor: '#FFFFFF',
		secondaryTintColor: '#6A7074',
		actionButtonColor:'#6A7074',
		auxiliaryTintColor: '#cdcdcd',
		actionTintColor: '#FFFFFF',
		separatorColor: '#2b2b2d',
		navbarBackground: '#6A7074',
		headerBorder: '#2F3234',
		headerBackground: '#6A7074',
		headerSecondaryBackground: '#6A7074',
		headerTintColor: isAndroid ? '#FFFFFF' : '#FFFFFF',
		headerTitleColor: '#FFFFFF',
		headerSecondaryText: isAndroid ? '#FFFFFF' : '#FFFFFF',
		toastBackground: '#0C0D0F',
		videoBackground: '#1f2329',
		favoriteBackground: '#ffbb00',
		hideBackground: '#54585e',
		messageboxBackground: '#6A7074',
		searchboxBackground: '#6A7074',
		buttonBackground: '#414852',
		buttonText: '#ffffff'
	},
	black: {
		backgroundColor: '#6A7074',
		focusedBackground: '#0d0d0d',
		chatComponentBackground: '#16181a',
		auxiliaryBackground: '#080808',
		bannerBackground: '#1f2329',
		titleText: '#f9f9f9',
		bodyText: '#e8ebed',
		backdropColor: '#000000',
		dangerColor: '#f5455c',
		successColor: '#2de0a5',
		borderColor: '#1f2329',
		controlText: '#dadde6',
		auxiliaryText: '#b2b8c6',
		infoText: '#6d6d72',
		tintColor: '#1e9bfe',
		auxiliaryTintColor: '#cdcdcd',
		actionTintColor: '#1ea1fe',
		secondaryTintColor: '#6A7074',
		separatorColor: '#272728',
		navbarBackground: '#0d0d0d',
		headerBorder: '#323232',
		headerBackground: '#0d0d0d',
		headerSecondaryBackground: '#0d0d0d',
		headerTintColor: isAndroid ? '#ffffff' : '#1e9bfe',
		headerTitleColor: '#f9f9f9',
		headerSecondaryText: isAndroid ? '#b2b8c6' : '#1e9bfe',
		toastBackground: '#0C0D0F',
		videoBackground: '#1f2329',
		favoriteBackground: '#ffbb00',
		hideBackground: '#54585e',
		messageboxBackground: '#0d0d0d',
		searchboxBackground: '#1f1f1f',
		buttonBackground: '#414852',
		buttonText: '#ffffff'
	}
};
